### ISSUE TITLE
A lurking defect

### ISSUE THREAD

**Issue by aegistudio** [nickallama/YoureAnAss#1]
It's open source and nice work, making terrible players asses.
I read your code to see how you turn a player into an ass, and found you're so clever.

It seems be a lurking defect that in OnCommand.java:25:

`   if(plugin.getServer().getPlayer(li.getPlayerUI()).getDisplayName() == p.getDisplayName())`

Be caution!

**Comment by nickallama** [comment]
Sorry for the lateish reply, been busy over the weekend.

Good spot and thank you! Did not notice it. Will fix and publish an update by tomorrow afternoon.

Thanks,

-Nick
